// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockUploader is an autogenerated mock type for the Uploader type
type MockUploader struct {
	mock.Mock
}

type MockUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploader) EXPECT() *MockUploader_Expecter {
	return &MockUploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: ctx, file, object
func (_m *MockUploader) Upload(ctx context.Context, file io.Reader, object string) error {
	ret := _m.Called(ctx, file, object)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) error); ok {
		r0 = rf(ctx, file, object)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockUploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - object string
func (_e *MockUploader_Expecter) Upload(ctx interface{}, file interface{}, object interface{}) *MockUploader_Upload_Call {
	return &MockUploader_Upload_Call{Call: _e.mock.On("Upload", ctx, file, object)}
}

func (_c *MockUploader_Upload_Call) Run(run func(ctx context.Context, file io.Reader, object string)) *MockUploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string))
	})
	return _c
}

func (_c *MockUploader_Upload_Call) Return(_a0 error) *MockUploader_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUploader_Upload_Call) RunAndReturn(run func(context.Context, io.Reader, string) error) *MockUploader_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUploader creates a new instance of MockUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploader {
	mock := &MockUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
